# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170327_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinghistory',
            name='date_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
