# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_shoppinghistory_date_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitems',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
