# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_shoppingcartitems_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartitems',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
