# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170330_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniqueproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
