# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_uniqueproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueproduct',
            name='quantity',
        ),
    ]
