# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_uniqueproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitems',
            name='extended_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rentalproduct',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
