# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20170404_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
