# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20170405_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='quantity_purchased',
            field=models.IntegerField(null=True),
        ),
    ]
