# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_uniqueproduct_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
