# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
